{"archive_info": {"hash": "sha256=f8ce0ed8e75fafa9f948e37548290cb8d188a154a17426b1a9ca01f39647cf08"}, "url": "https://files.pythonhosted.org/packages/db/b7/2ebe2a6f154a525465d5fe181ccc4b9d570d5210ac337a450b9b1ed21333/exception-0.1.0-py2.py3-none-any.whl"}